export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DECREASE_PRODUCT_QTY = 'DECREASE_PRODUCT_QTY';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const INCREASE_PRODUCT_QTY = 'INCREASE_PRODUCT_QTY';
export const SORT_PRODUCT = 'SORT_PRODUCT';
export const MOVE_ITEM = 'MOVE_ITEM';